# Generated by Django 3.2 on 2021-07-12 01:05

import app_users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0003_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, default='static/Images/user_avatar.png', upload_to=app_users.models.path_and_rename, verbose_name='Profile Picture'),
        ),
    ]
